### ISSUE TITLE
installation of generator-liferay-theme on Windows

### ISSUE THREAD

**Issue by vernaillen** [natecavanaugh/generator-liferay-theme#1]
Hi Nate,
I was trying to install generator-liferay-theme on a Windows, but I ran into a couple of issues.
First I had to install Python, which is not really an issue, but it seems mandatory. 
Then I had this error: "self signed certificate in certificate chain". I could get around it by setting NODE_TLS_REJECT_UNAUTHORIZED=0, but this is not really safe. I'm not sure if my customer's firewall had impact in this or not.
The next error I got is this: MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe".
It seems that node-gyp requires Visual Studio to be installed, as explained here: https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

I will continue installing all the required Microsoft tools, but it's definitely a lot of hassle. I guess the people running Windows last Wednesday in the workshop ran into these same issues?

Maybe it would be good to point to these links in the readme?
https://github.com/nodejs/node-gyp#installation
https://github.com/nodejs/node-gyp/wiki/Visual-Studio-2010-Setup

Let me know if there's anything else I can do to help testing the new theming tools.

**Comment by natecavanaugh** [comment]
Hi Wouter,
Thanks for testing out the new tools on Windows, as well as filing the issue. All of that definitely seems like a pain :( It's too bad that node-gyp requires so much setup before getting it to work.
While there's not much we can do from the node-gyp side, I agree, that we can document it in the README.
One other option, and I'm not sure which one would be more of a pain in your opinion, would be to use the Ruby version of Sass.
We only load node-sass if you don't select the option "Do you need Compass support?". If that one's chosen, we assume you have the ruby version already installed, and use that package.
So it would be a matter of installing Ruby, and installing the Sass and Compass gems, which, depending on preference, might be an easier initial kick start.
I'll document that in the README as well as another alternative.
Thanks again for filing this :)

**Comment by natecavanaugh** [comment]
Also, wrt the SSL issue, I do think it was likely a firewall issue, as I have only run into an issue like that when using a proxy to debug https API calls.
However, it might be worth trying it off of the network to verify.
